name: climateclock

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Render page
        run: |
          docker run --rm -v "$(pwd)":/data wkhtmltopdf/wkhtmltoimage:latest \
          wkhtmltoimage --format png --quality 100 clock.html clock.png

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add clock.png
          git commit -m "chore: clock update"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
